---

# common
- hosts: all
  sudo: yes
  #become_user: root
  gather_facts: no
  #become: yes
  #become_method: sudo

  tasks:

  - name: install git
    apt: name=git state=present update_cache=yes

# web
- hosts: web
  sudo: yes
  #become_user: root
   
  

  tasks:

  - name: install nginx
    apt: name=nginx state=present

  - name: write our nginx.conf
    template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify: restart nginx

  - name: write our /etc/nginx/sites-available/default
    template: src=templates/default-site.j2 dest=/etc/nginx/sites-available/default
    notify: restart nginx

  - name: deploy website content
    template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html

  handlers:

  - name: restart nginx
    service: name=nginx state=restarted

# lb
- hosts: lb
  sudo: yes
  #become_user: root
  #become_method: sudo
   
  

  tasks:

  - name: install haproxy and socat
    apt: 
       name:
         - haproxy
         - socat
       state: latest
       autoclean: yes
       
    

  - name: enable haproxy
    lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
    notify: restart haproxy 

  - name: deploy haproxy config
    template: src=templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
    notify: restart haproxy

  handlers:

  - name: restart haproxy
    service: name=haproxy state=restarted
